### ISSUE TITLE
Principle representative requirement is 0.1% of online stake, not available supply

### ISSUE THREAD

**Issue by qwahzi** [georgehara/nano#2]
Per this clarification from Zach of the Nano foundation:

> Due to miscommunication about the existing voting weight minimums for Principal Representatives, we made updates to our documentation to clarify these limits today. What has been communicated to date is that nodes need 0.1% of the available **supply** (approximately 133,248 Nano) to become a Principal Representative ([https://docs.nano.org/glossary/#principal-representative](https://docs.nano.org/glossary/#principal-representative)) but this is inaccurate. **The 0.1% limit actually applies to the lower value of **online stake** and thus makes the target minimum for Principal Representatives more dynamic.** At the moment, this means \~115,000 Nano is required.
> 
> 
> Third-party services that are tracking and marking nodes as Principal Representatives may need to adjust their logic to be accurate, which may take some time to complete. The minimum value (in raw) can be found by calling the confirmation\_quorum RPC ([https://docs.nano.org/commands/rpc-protocol/#confirmation\_quorum](https://docs.nano.org/commands/rpc-protocol/#confirmation_quorum)) and dividing the returned online\_stake\_total by 1000. As the online stake is trended over time and only sampled every 5 mins, accurate tracking of this value should be very lightweight for systems.
> 
>   
> We are looking into updates to RPC calls to make this easier including a dedicated minimum\_principal\_weight call to return the value, which will help if the rules change in the future. We are also looking at including a flag on RPCs representatives and representatives\_online to return principal status for each rep.  Any feedback on these is welcome.
> 
>   
> We apologize for any confusion this may have caused but are glad that this results in a lower bar for becoming a Principal Representative - in fact, this means the following representatives are over the PR limit even though they haven't been reported as such on various services, with others getting closer as well:
> 
> * [https://mynano.ninja/account/nano\_1kd4h9nqaxengni43xy9775gcag8ptw8ddjifnm77qes1efuoqikoqy5sjq3](https://mynano.ninja/account/nano_1kd4h9nqaxengni43xy9775gcag8ptw8ddjifnm77qes1efuoqikoqy5sjq3)
> * [https://mynano.ninja/account/nano\_3nnogsx1u7ye6snntq9fi1aakb489dsk94zyex8fdd5ioubmhep3o9sr7zsk](https://mynano.ninja/account/nano_3nnogsx1u7ye6snntq9fi1aakb489dsk94zyex8fdd5ioubmhep3o9sr7zsk)

https://www.reddit.com/r/nanocurrency/comments/cjf2l1/clarifying_the_requirements_for_becoming_a/

**Comment by georgehara** [comment]
Thank you for the comment. There were about 2 places where this information was correct, and 3 where it was wrong (forgot to change it).
